version: '3.7'

services:

  mysql-master:
    image: mysql
    # 容器命名
    container_name: mysql-master
    # 环境变量，mysql要求提供，根据此密码可以进入容器mysql中
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: new_ink_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./master/data/:/var/lib/mysql/
      - ./master/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - db-net

  mysql-slave:
    image: mysql
    # 容器命名为从数据库
    container_name: mysql-slave
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_ink_db
    volumes:
      - ./slave/data/:/var/lib/mysql/
      - ./slave/my.cnf:/etc/mysql/my.cnf
    # 将容器端口映射到宿主机端口，可以声明也可以不声明，一般情况下不会将后端端口直接暴露出去
    ports:
      - "3307:3306"
    networks:
      - db-net

networks:
  db-net:
    driver: bridge